<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgLogoHeader</name>
   <tag></tag>
   <elementGuidId>661a42d7-312e-4626-b524-0452f1127d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='The Movie Database (TMDB)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;The Movie Database (TMDB)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bbec9d2a-9c3a-4c9f-88b4-6e3b60ed2b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg</value>
      <webElementGuid>614d3f1b-63db-4087-a876-53202008952a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Movie Database (TMDB)</value>
      <webElementGuid>db7d0767-d96b-4c1a-8097-10f56eca6303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>154</value>
      <webElementGuid>ca019974-7a3d-42ac-84bf-c1fd07bab271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6dbf36a0-696f-4976-8172-e20d26140bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js k-webkit k-webkit116&quot;]/body[@class=&quot;en v4&quot;]/div[@class=&quot;page_wrap _wrap&quot;]/header[@class=&quot;normal smaller no_animation smaller  subtle&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;sub_media&quot;]/div[@class=&quot;nav_wrapper&quot;]/a[@class=&quot;logo&quot;]/img[1]</value>
      <webElementGuid>1832037c-da68-4146-b532-47aae1ffa1a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='The Movie Database (TMDB)']</value>
      <webElementGuid>75596c74-46f3-45d9-80e6-48e5a4dfc821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7320f27d-ce92-4cdc-8869-3fe469861add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg' and @alt = 'The Movie Database (TMDB)']</value>
      <webElementGuid>b25d64c4-f195-4587-b431-0a00b5e4f38c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
