<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchResultTexttBarbie</name>
   <tag></tag>
   <elementGuidId>1e01f849-90b4-47ea-b1f2-621e7f321ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='card_movie_5590ddde925141758c00022d']/div/div[2]/div/div/div/a/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>941996be-2346-4a87-b240-96fc5fa9fd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Barbie</value>
      <webElementGuid>40300bbd-2b61-4e73-aa80-19bdff17dda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_movie_5590ddde925141758c00022d&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;details&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;title&quot;]/div[1]/a[@class=&quot;result&quot;]/h2[1]</value>
      <webElementGuid>df352c38-2c70-49e9-9c6b-45b9e4d82697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card_movie_5590ddde925141758c00022d']/div/div[2]/div/div/div/a/h2</value>
      <webElementGuid>16de249c-ea96-49ba-beb2-1c58522ba0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Networks'])[1]/following::h2[1]</value>
      <webElementGuid>72ae5eb2-8af5-4fe6-a982-42616818a874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::h2[1]</value>
      <webElementGuid>2913fcbd-3d26-4b32-9f4e-68b62ed78378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 19, 2023'])[1]/preceding::h2[1]</value>
      <webElementGuid>09548d27-cf0e-4f70-b3d0-95f97c39bb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barbie'])[2]/preceding::h2[1]</value>
      <webElementGuid>18666b9a-f3bf-443d-8cbf-a99d244ee3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Barbie']/parent::*</value>
      <webElementGuid>f4513087-3041-4da7-ab19-695e08d9a9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>2230cba6-6f31-445f-a40a-aa3f52519347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Barbie' or . = 'Barbie')]</value>
      <webElementGuid>f19fea43-bd7d-47e3-b184-449b8bd427cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
