<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgTrendingPoster2</name>
   <tag></tag>
   <elementGuidId>2f457048-8943-4e23-9105-165545d770f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trending_scroller']/div/div[5]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>80183c68-3a88-4137-8f87-571832315191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>182a8a09-16d0-4266-b1f3-0fb9795a03e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poster</value>
      <webElementGuid>57f76c80-604a-4c1b-a9f8-7269c78d92d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/t/p/w220_and_h330_face/zTTgI92GGVtYIGunown2oWOUDES.jpg</value>
      <webElementGuid>2fc70c80-5db5-40a2-a67e-1aa8b194855a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/t/p/w220_and_h330_face/zTTgI92GGVtYIGunown2oWOUDES.jpg 1x, /t/p/w440_and_h660_face/zTTgI92GGVtYIGunown2oWOUDES.jpg 2x</value>
      <webElementGuid>ea6bf03b-510f-40ea-84e0-3dc077b2d2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trending_scroller&quot;)/div[@class=&quot;column_content flex scroller loaded&quot;]/div[@class=&quot;card style_1&quot;]/div[@class=&quot;image&quot;]/div[@class=&quot;wrapper&quot;]/a[@class=&quot;image&quot;]/img[@class=&quot;poster&quot;]</value>
      <webElementGuid>0e2c54e1-3be5-41f4-8d62-e76933079d5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trending_scroller']/div/div[5]/div/div/a/img</value>
      <webElementGuid>73e4ef60-1558-4d35-982c-76ff267843a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a/img</value>
      <webElementGuid>9009a30f-abc5-4370-8c92-ae130fc8dd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/t/p/w220_and_h330_face/zTTgI92GGVtYIGunown2oWOUDES.jpg']</value>
      <webElementGuid>feef1172-3a05-4476-9078-3a9a800dfcc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
