<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgTrendingPoster</name>
   <tag></tag>
   <elementGuidId>3bee687c-a001-42cd-95c5-d79fb0e74837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trending_scroller']/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.poster</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>09d7c554-3faf-49d0-b486-eb49bbd2b5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>500fbcf6-b8d7-44fc-8757-ed0bc04aa2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poster</value>
      <webElementGuid>50ecfb7a-9efc-4754-ac17-e19f312ea9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/t/p/w220_and_h330_face/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg</value>
      <webElementGuid>292b9374-3d60-4998-b664-8bd8991e353c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/t/p/w220_and_h330_face/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg 1x, /t/p/w440_and_h660_face/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg 2x</value>
      <webElementGuid>a2493bd8-a7e8-475f-bfec-1574f2766eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trending_scroller&quot;)/div[@class=&quot;column_content flex scroller loaded&quot;]/div[@class=&quot;card style_1&quot;]/div[@class=&quot;image&quot;]/div[@class=&quot;wrapper&quot;]/a[@class=&quot;image&quot;]/img[@class=&quot;poster&quot;]</value>
      <webElementGuid>b801045b-fc0c-4979-9389-ddc6476bf32f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trending_scroller']/div/div/div/div/a/img</value>
      <webElementGuid>d0e16f82-013a-4c10-a3ea-e26fec10dd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a/img</value>
      <webElementGuid>fc8b33cd-d45e-4016-b505-63a9738f8a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/t/p/w220_and_h330_face/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg']</value>
      <webElementGuid>2936da0a-94ad-4893-8602-894321c6e80c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
