<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_notFoundUsername</name>
   <tag></tag>
   <elementGuidId>15dbf9d4-cb08-42df-9ca9-80623ec0f499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/section/div/div/div/div/div/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content > ul > li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>387573b5-b3eb-4771-b6e9-c9f497892ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We couldn't find your username.</value>
      <webElementGuid>39399031-2919-48d0-9b10-126bc281f263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/section[@class=&quot;main_content content&quot;]/div[@class=&quot;column_wrapper&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;error_status card&quot;]/div[@class=&quot;carton&quot;]/div[@class=&quot;content&quot;]/ul[1]/li[1]</value>
      <webElementGuid>82080fc6-79c0-41ee-a04c-ca8d01474f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/section/div/div/div/div/div/div/ul/li</value>
      <webElementGuid>b6f1c2fb-a73c-4c0d-b428-cfa137fbe75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click here'])[1]/following::li[1]</value>
      <webElementGuid>33b40aa3-e438-4737-b43e-dbe35009a57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have 9 remaining login attempts.'])[1]/preceding::li[1]</value>
      <webElementGuid>2b5025f8-31ef-47f1-b29c-90c7b32d9b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::li[2]</value>
      <webElementGuid>c3162057-50df-46ea-a149-131714633251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li</value>
      <webElementGuid>9ae922ae-2c92-44ca-907e-ca8b63e6d6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = concat(&quot;We couldn&quot; , &quot;'&quot; , &quot;t find your username.&quot;) or . = concat(&quot;We couldn&quot; , &quot;'&quot; , &quot;t find your username.&quot;))]</value>
      <webElementGuid>b4057dda-55d9-432f-881a-21abf1ced6ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
