<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addWatchlistButton</name>
   <tag></tag>
   <elementGuidId>6a4ca96f-de2c-49a0-ad01-72d93f5ae380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#watchlist</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='watchlist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e16c3aca-b268-40ad-bdca-0f19e89e0477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>watchlist</value>
      <webElementGuid>3060154f-d161-4ccc-ac3b-9acfebeb9ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_click add_to_account_list watchlist</value>
      <webElementGuid>4e7c1a85-a31c-42f8-9b83-8a1e765b6a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9540f74f-0c82-469f-9a19-3c58b308b822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;watchlist&quot;)</value>
      <webElementGuid>f8203094-2b44-4a12-b70f-b4dce3de01c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='watchlist']</value>
      <webElementGuid>1723c8ca-90c9-4a82-8629-366eba6080f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='original_header']/div[2]/section/ul/li[4]/a</value>
      <webElementGuid>de1a5ae4-959b-47e3-82ee-6cfef62607da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UserScore'])[1]/following::a[3]</value>
      <webElementGuid>f3774cc6-0b6a-4376-abad-dcf414946b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drama'])[1]/following::a[3]</value>
      <webElementGuid>b918ad7e-687f-4c4b-819c-dcf81ae16305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[3]/preceding::a[3]</value>
      <webElementGuid>be0b7ccc-a213-4abb-a86a-281b511db56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vanessa Caswill'])[1]/preceding::a[3]</value>
      <webElementGuid>8e5a030a-f717-4c46-83cc-219b20320112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>1e2552cc-0745-490b-bf7a-79fee1d837a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li[4]/a</value>
      <webElementGuid>e7c88291-a163-4624-b9ea-143c12016113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'watchlist' and @href = '#']</value>
      <webElementGuid>ee34a5c4-9fbc-407f-96a8-68e9908bb51d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
