<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>favoriteMovieButton</name>
   <tag></tag>
   <elementGuidId>25904033-08aa-4301-b62d-f9d754c14989</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#favourite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='favourite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72e25955-eb1f-4116-a3ad-03eaf4b9fd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>favourite</value>
      <webElementGuid>a27cda67-958f-4db2-a41b-71bc34a4cab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_click add_to_account_list favourite</value>
      <webElementGuid>0452fcce-e8b3-44be-8050-a84ae09a23d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c7bcd51b-1ef4-4156-9fe7-2e80c4347890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;favourite&quot;)</value>
      <webElementGuid>49013d7b-545f-489e-856d-e74759cd32b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='favourite']</value>
      <webElementGuid>3fbabf80-70ad-4bb8-9b45-d0c81e1fd384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='original_header']/div[2]/section/ul/li[3]/a</value>
      <webElementGuid>a7108ab9-84bb-4440-9659-83217f4ef19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UserScore'])[1]/following::a[2]</value>
      <webElementGuid>ad8c18b0-55e3-4b42-9a5c-5a60e10e87f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fantasy'])[1]/following::a[2]</value>
      <webElementGuid>cbcb85c5-858b-4774-b4f5-a5afd527634a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('She', &quot;'&quot;, 's everything. He', &quot;'&quot;, 's just Ken.')])[1]/preceding::a[4]</value>
      <webElementGuid>92c3c899-1a58-4672-a67f-7ac4dea7690a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[3]/preceding::a[4]</value>
      <webElementGuid>721e19a6-cc4f-453a-852e-5cce9e10a5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>8d34ca88-3d7b-4571-8a05-f895d9ccf0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li[3]/a</value>
      <webElementGuid>229e851c-4e3a-474c-bf58-0e0dd53203b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'favourite' and @href = '#']</value>
      <webElementGuid>eae7e763-4ac6-43c5-825f-3e019e3e5c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
