<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rateMovieButton</name>
   <tag></tag>
   <elementGuidId>42c9b981-2ab9-40d5-9014-1d87b837f7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rate_it</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rate_it']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>621db238-d126-41f7-a575-351a825516b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rate_it</value>
      <webElementGuid>a9bf72d9-c3da-42c5-aa34-85279145997b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_click rating</value>
      <webElementGuid>5925f382-416d-473b-9e51-d055c231918e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>194cc54d-1d1b-4f0c-b72b-26982bd1465b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rate_it&quot;)</value>
      <webElementGuid>52499a18-cbb9-468b-8323-4e3e20fb9a9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rate_it']</value>
      <webElementGuid>0b3aa3b9-e56b-4e18-8ef4-1599240a2b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='original_header']/div[2]/section/ul/li[5]/a</value>
      <webElementGuid>26fc0f52-ff94-4eef-90b3-f1eef1b9ae45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UserScore'])[1]/following::a[4]</value>
      <webElementGuid>cf1afb18-6e4b-487f-9b14-fd2e7c67da68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drama'])[1]/following::a[4]</value>
      <webElementGuid>1974e2b7-36f1-4a3a-a244-1a4820420b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[3]/preceding::a[2]</value>
      <webElementGuid>2236ecd6-26ba-4dc0-957b-4e36b152daef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vanessa Caswill'])[1]/preceding::a[2]</value>
      <webElementGuid>bf4c812b-e956-4454-96b2-206d9c29df61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>43137ba3-7c3e-447a-b54d-b0ba80ee0dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li[5]/a</value>
      <webElementGuid>951ef77d-dd86-4203-b066-124bd3f900ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rate_it' and @href = '#']</value>
      <webElementGuid>175380f1-a181-4181-a574-3d4165a1405f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
